In [634]:
import numpy as np

In [635]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

Importing the data

In [636]:
raw_data_np = np.genfromtxt('loan-data.csv', delimiter=';',autostrip=True, skip_header=1, encoding='ISO-8859-1')
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Checking for incomplete data

In [637]:
np.isnan(raw_data_np).sum()

88005

In [638]:
temp_fill = np.nanmax(raw_data_np)+1
temp_mean = np.nanmean(raw_data_np, axis=0)
print(temp_fill)
print(temp_mean)


68616520.0
[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
         nan         nan         nan         nan         nan     3143.85]


C:\Users\Suhas\AppData\Local\Temp\ipykernel_10552\351673926.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis=0)


In [639]:
temp_stats = np.array([np.nanmin(raw_data_np, axis=0),
                        temp_mean,
                        np.nanmax(raw_data_np, axis=0)])

C:\Users\Suhas\AppData\Local\Temp\ipykernel_10552\413738982.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_np, axis=0),
C:\Users\Suhas\AppData\Local\Temp\ipykernel_10552\413738982.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis=0)])


In [640]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

Splitting the dataset

splitting the columns

In [641]:
column_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [642]:
column_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

Reimporting the dataset

In [643]:
loan_data_strings = np.genfromtxt('loan-data.csv',
                                  delimiter=';',
                                  skip_header=1,
                                  autostrip=True,
                                  usecols=column_strings,
                                  dtype=str,
                                  encoding='ISO-8859-1')

In [644]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [645]:
loan_data_numeric = np.genfromtxt('loan-data.csv',
                                  delimiter=';',
                                  skip_header=1,
                                  autostrip=True,
                                  usecols=column_numeric,
                                  encoding='ISO-8859-1',
                                  filling_values=temp_fill)

In [646]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

Name of the column

In [647]:
header_full = np.genfromtxt('loan-data.csv',
                                  delimiter=';',
                                  skip_footer= raw_data_np.shape[0],
                                  autostrip=True,
                                  dtype=str,
                                  encoding='ISO-8859-1')

In [648]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [649]:
header_string, header_numeric = header_full[column_strings], header_full[column_numeric]

In [650]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [651]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

creating checkpoints

In [652]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name+".npz")
    return checkpoint_variable

In [653]:
checkpoint_test = checkpoint('checkpoit_test', header_string, loan_data_strings)

In [654]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [655]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [656]:
np.array_equal(checkpoint_test['data'],loan_data_strings)

True

Manipulatig the string column

In [657]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [658]:
header_string[0] = 'issue_date'

In [659]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [660]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

Issue Date

In [661]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [662]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],'-15')

In [663]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [664]:
# replacing the month string to number

months = np.array(['', 'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

for i in range(13):
             loan_data_strings[:,0] = np.where(loan_data_strings[:,0]==months[i],
                                                          i,
                                                          loan_data_strings[:,0])        
        

In [665]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

loan status

In [666]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [667]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [668]:
# we will assign the loan status as good and bad status, for good =1 and bad =0

np.unique(loan_data_strings[:,1]).size

9

In [669]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [670]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

Term

In [671]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [672]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [673]:
# we will strip the months part from the term column
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2],' months')

# renameing the header of term to term_months
header_string[2] = 'term_months'

In [674]:
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [675]:
# replacing the empty string to 60 as it is long period term
loan_data_strings[:,2] = np.where(loan_data_strings[:,2]=='',
                                  '60',
                                  loan_data_strings[:,2])
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

Grade and subgrade

In [676]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [677]:
np.unique(loan_data_strings[:,3], return_counts = True)

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array([ 515, 1632, 2606, 2766, 1389,  816,  236,   40], dtype=int64))

In [678]:
np.unique(loan_data_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

Filling sub grade

In [679]:
np.unique(loan_data_strings[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [680]:
# checking the grade and subgrade and if grade has value like 'A' but subgrade has empty string then the subgrade will assign to the last subgrade like 'A5' 
# so that borrower can safe from worst possible subgrade.
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4]=='') & (loan_data_strings[:,3]==i),
                                      i+'5',
                                      loan_data_strings[:,4])

In [681]:
np.unique(loan_data_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [682]:
# create new H1 subgrade. assign the empty subgrade string to H1
loan_data_strings[:,4] = np.where(loan_data_strings[:,4]=='',
                                  'H1',
                                  loan_data_strings[:,4])
np.unique(loan_data_strings[:,4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

Rempving grade

In [683]:
loan_data_strings = np.delete(loan_data_strings,3,axis=1)

In [684]:
header_string = np.delete(header_string,3)

In [685]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [686]:
header_string[3]

'sub_grade'

converting the subgrade

In [687]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [688]:
np.unique(loan_data_strings[:,3]).shape

(36,)

In [689]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_sub_grade = dict(zip(keys,values))

In [690]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [691]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                      dict_sub_grade[i],
                                      loan_data_strings[:,3])

np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

Verification status

In [692]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [693]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [694]:
# for '', 'Not Verified' = 0 and for 'Source Verified', 'Verified' = 1

loan_data_strings[:,4] = np.where((loan_data_strings[:,4]== '') | (loan_data_strings[:,4] == 'Not Verified'),
                                  0,
                                  1)

In [695]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

URL

In [696]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [697]:
#deleting the repeating url upto loan_id
loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [698]:
#since the id from url (string) and id form id column(numeric) are same, we will first check and delete the url column
# type casting the url and id column to int

loan_data_numeric[:,0].astype(dtype=np.int32)
loan_data_strings[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [699]:
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32),loan_data_strings[:,5].astype(dtype=np.int32))

True

In [700]:
loan_data_strings = np.delete(loan_data_strings,5,axis=1)
header_string= np.delete(header_string,5)

In [701]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [702]:
header_string[5]

'addr_state'

Sate address

In [703]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [704]:
header_string[5] = 'state_address'

In [705]:
state_name, state_count = np.unique(loan_data_strings[:,5], return_counts = True)

In [706]:
state_name

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [707]:
state_count

array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
         84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
        341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
         17,  216,  148,   49,   27], dtype=int64)

In [708]:
# taking the state_count indices in decresing order. 
states_count_sorted = np.argsort(-state_count)

state_name[states_count_sorted],state_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [709]:
#replacing the empty string with 0
loan_data_strings[:,5] = np.where(loan_data_strings[:,5]=='',
                                  0,
                                  loan_data_strings[:,5])

In [710]:
#sorting the state list according to the region
state_west = np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
state_east = np.array(['ME','NH','VT','MA','RI','CT','NY','PA','NJ'])
state_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
state_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])

In [711]:
# assigning state_west = 1, state_south = 2, state_midwest=3, state_east=4 
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], state_west),1,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], state_south),2,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], state_midwest),3,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], state_east),4,loan_data_strings[:,5])

In [712]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [713]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [714]:
# type casting to int
loan_data_strings = loan_data_strings.astype(int)
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

checkpoint string

In [715]:
checkpoint_string = checkpoint('checkpoint_string',header_string,loan_data_strings)

In [716]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [717]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [718]:
np.array_equal(loan_data_strings,checkpoint_string['data'])

True

Manipulating numeric columns

In [719]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [720]:
np.isnan(loan_data_numeric).sum()

0

substitute "filler" values

In [721]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

id

In [722]:
temp_fill

68616520.0

In [723]:
#chech the temp_fill value is prresent in id column
np.isin(loan_data_numeric[:,0],temp_fill)

array([False, False, False, ..., False, False, False])

In [724]:
np.isin(loan_data_numeric[:,0],temp_fill).sum()

0

In [725]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

temporary stats

In [726]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [727]:
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [728]:
#firt row is min value
#second row is mean value
#third row is max value
# all this values are for numeric column
temp_stats[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

for funded_amt min value is consider worst and for all max is consider worst


In [729]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [730]:
#replacing the temp_fill value with min value from temp_stats 1st row and 3rd column from column numeric
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2]==temp_fill,
                                  temp_stats[0,column_numeric[2]],
                                  loan_data_numeric[:,2])

In [731]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

Loaned amt, interest rate, payment, installment

In [732]:
#replacing the temp_fill values from Loaned amt, interest rate, payment, installment column to max value of resp column from temp_stats
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i]==temp_fill,
                                      temp_stats[2,column_numeric[i]],
                                      loan_data_numeric[:,i])

In [733]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

currency exchange

exchange rate

In [734]:
# this eur_usd file content the average monthly exchange rate of eur to usd for 2015
eur_usd = np.genfromtxt('EUR-USD.csv',delimiter=',',autostrip=True,dtype=str)
eur_usd

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [735]:
#only closing rate is required hence, we are not using the rest of the data
eur_usd = np.genfromtxt('EUR-USD.csv',delimiter=',',autostrip=True,usecols=3,skip_header=1)
eur_usd


array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [736]:
#month
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [737]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [738]:
# issue_date column has a date format in 1 to 12 and 0 for nan.
# creating new variable exchange_rate of issue_date column 
# assinging the avg exchange rate of the month to the exchange_rate column

exchange_rate = loan_data_strings[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             eur_usd[i-1], #1to12
                             exchange_rate)

# if the issue_date is nan, assign the average exchange rate of the year to the exchange_rate column
exchange_rate = np.where(exchange_rate ==0,
                         np.mean(eur_usd),
                         exchange_rate)


In [739]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [740]:
exchange_rate.shape # 1D array

(10000,)

In [741]:
loan_data_numeric.shape #2D array

(10000, 6)

In [742]:
# we have to reshape the exchange_rate array to a 2D array
exchange_rate = np.reshape(exchange_rate, (len(exchange_rate), 1))
exchange_rate.shape

(10000, 1)

In [743]:
# horizontal stacking to numeric data
loan_data_numeric=np.hstack((loan_data_numeric, exchange_rate))

In [744]:
#concatinating the exchange_rate as header to header numeric aaray.
header_numeric = np.concatenate((header_numeric,np.array(['exchange_rate']))) 
header_numeric


array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

From usd to eur

In [745]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [746]:
# all tranction amt column indeces stored in column_dollar variable 

column_dollar = np.array([1,2,4,5])

In [747]:
loan_data_numeric[:,[column_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [748]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [749]:
# for i in column_dollar:
#     loan_data_numeric = np.hstack((loan_data_numeric,loan_data_numeric[:,i]/loan_data_numeric[:,6]))
    

In [750]:
# loan_data_numeric[:,i]/loan_data_numeric[:,6] we have to reshape the to 2D array i.e length of loan_data_numeric,1
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(len(loan_data_numeric),1))))


In [751]:
loan_data_numeric.shape

(10000, 11)

In [752]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

expanding the header

In [753]:
# concatinating 'EUR' to the column_dollar column and storing it to new variable header_additional, so that we can use this variable to give name to the new column
header_additional = np.array([column_name+'_EUR' for column_name in header_numeric[column_dollar]])

In [754]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [755]:
#concatanating this additional headers to the existing headers numeric
header_numeric = np.concatenate((header_numeric,header_additional))

In [756]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [757]:
#now overriding the header numeric and concatinating column_dollar to '_USD' 
header_numeric[column_dollar] = np.array([column_name+'_USD' for column_name in header_numeric[column_dollar]])

In [758]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [759]:
#we will arrange the column so that each EUR column follows its corresponding USD column
column_order_index = [0,1,7,2,8,3,4,9,5,10,6]

In [760]:
header_numeric = header_numeric[column_order_index]
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [761]:
loan_data_numeric = loan_data_numeric[:,column_order_index]
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

interest rate

In [762]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [763]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [764]:
#an interest rate usually dictates using values between 0 and 1, we will divide by 100 to convert to a percentage
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

checkpoint 2: numeric

In [766]:
checkpoint_numeric = checkpoint('checkpoint_numeric',header_numeric,loan_data_numeric)

In [767]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [768]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

creating the 'Complete' dataset

In [770]:
#must have comapatible shapes
checkpoint_string['data'].shape

(10000, 6)

In [771]:
checkpoint_numeric['data'].shape

(10000, 11)

In [772]:
#horizontal stack
np.hstack((checkpoint_numeric['data'],checkpoint_string['data']))

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [773]:
np.hstack((checkpoint_numeric['data'],checkpoint_string['data'])).shape

(10000, 17)

In [774]:
loan_data = np.hstack((checkpoint_numeric['data'],checkpoint_string['data']))

In [775]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [777]:
#check if it has null values
np.isnan(loan_data).sum()

0

In [780]:
#concatanating the numeric header and string header
header_full = np.concatenate((checkpoint_numeric['header'],checkpoint_string['header']))
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

sorting the new dataset

In [781]:
# sorting the array according to the id column
# we will use argsort() method to get the indices of the sorted array
# then we will use these indices to sort the original array
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data


array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [783]:
# check the indices of id column using argsort() 
np.argsort(loan_data[:,0]) #  returns the indices that would sort the array


array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [785]:
# vertical stacking of header_full
loan_data=np.vstack((header_full, loan_data))

storing the new dataset

In [786]:
np.savetxt('loan-data-preprocess.csv',loan_data, fmt='%s',delimiter=',')